version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: master

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:18.0.1
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn clean test
      - codecov/upload
      - run: mvn checkstyle:check
      - run: mvn checkstyle:checkstyle-aggregate


